name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Adjust to your required Go version

      - name: Set up just
        uses: extractions/setup-just@v2

      - name: Build reddituit
        run: just build

      - name: Run tests
        run: just test
