name: Deploy reddittui

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
          - os: macos-latest
            goos: darwin
            goarch: amd64
            ext: ""
          - os: macos-latest
            goos: darwin
            goarch: arm64
            ext: ""
    runs-on: ${{ matrix.os }}

    env:
      BUILD_DIR: build
      BINARY_PREFIX: reddittui

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ${{ env.BUILD_DIR }}/${{ env.BINARY_PREFIX }}${{ matrix.ext }} .

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_PREFIX }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ env.BUILD_DIR }}/${{ env.BINARY_PREFIX }}${{ matrix.ext }}
